# Настройки среды
image: ubuntu2204  # Используемый образ (Ubuntu 22.04)

# Переменные окружения
environment:
  DOCKER_PASSWORD: 240304Kmd_
  DOCKER_USERNAME: pechenka1
  PROJECT_NAME: "lab_2"  # Название вашего проекта на Railway

# Сборка Docker-образа
build_script:
  - docker compose -f docker_compose.yml up --build -d   # Сборка Docker-образа

on_finish:
  - docker compose -f docker_compose.yml down  # Остановка и удаление контейнера